title: What is Composer
content: Composer is a powerful build system and content pipeline for generating documentation, websites, and structured content from multiple data sources.
category: intro
weight: 1